### ISSUE TITLE
Obélix repo

### ISSUE THREAD

**Issue by alantudyk** [eclipseo/eclipseo.github.io#6]
I'm adding several images into the repo on GitHub: "Is it fair if I use a free account?"
Robert-André Mauchin: "YES, OF COURSE! WHY DO YOU ASK?"
```
$ git clone https://github.com/eclipseo/eclipseo.github.io.git
...
Receiving objects: 100% (15978/15978), 12.99 GiB
...
```
You can consider this issue as a fat-shaming.

**Comment by eclipseo** [comment]
> I'm adding several images into the repo on GitHub: "Is it fair if I use a free account?" Robert-André Mauchin: "YES, OF COURSE! WHY DO YOU ASK?"
> 
> ```
> $ git clone https://github.com/eclipseo/eclipseo.github.io.git
> ...
> Receiving objects: 100% (15978/15978), 12.99 GiB
> ...
> ```
> 
> You can consider this issue as a fat-shaming.

Well I use a DigitalOcean account afterwards. I should purge the history maybe.
